create table if not exists public.claims (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.found_items(id) on delete cascade,
  claimant_email text not null,
  claim_message text not null check (char_length(trim(claim_message)) > 0),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

create unique index if not exists claims_one_pending_claim_per_item_and_user
  on public.claims (item_id, claimant_email)
  where status = 'pending';

alter table public.claims enable row level security;

create policy "Claimants can submit their own pending claims"
  on public.claims
  for insert
  to authenticated
  with check (
    claimant_email = auth.jwt() ->> 'email'
    and status = 'pending'
  );

create policy "Claimants can read their claims and admins can read all claims"
  on public.claims
  for select
  to authenticated
  using (
    claimant_email = auth.jwt() ->> 'email'
    or exists (
      select 1
      from public.profiles
      where profiles.email = auth.jwt() ->> 'email'
        and profiles.role = 'admin'
    )
  );

create policy "Admins can update claims"
  on public.claims
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.email = auth.jwt() ->> 'email'
        and profiles.role = 'admin'
    )
  )
  with check (
    exists (
      select 1
      from public.profiles
      where profiles.email = auth.jwt() ->> 'email'
        and profiles.role = 'admin'
    )
  );
